### ISSUE TITLE
feature request - highlight new additions

### ISSUE THREAD

**Issue by ColinEberhardt** [torch2424/made-with-webassembly#28]
You [mentioned on twitter](https://twitter.com/torch2424/status/1201946191820247040) that you've added a bunch of new projects - perhaps you could add a 'new' badge to projects for a few weeks to make the new entries easier to find?

**Comment by torch2424** [comment]
@ColinEberhardt Sorry for the late reply, been dealing with some wild work stuff!

Totally! I agree with this, I think that would be awesome to highlight newly added projects 😄 👍 

I think maybe I can add a page called like "Newly added"? And keep it a maximum of like 5-10 projects? 🤔 Just because right now the list is randomized everytime you visit, and I kind of like that, as it's a subtle UX that makes you see some new projects every time? But I may be wrong here haha 😂 

Either way, Thanks for the suggestion!
